title: PMLR Volume 2
description: > # this means to ignore newlines until "baseurl:"
    Proceedings of AISTATS 2007
baseurl: "/v1"
volume: 2
date: 2007-10-27
url: "http://proceedings.mlr.press"
twitter_username: mlresearch
github_username:  mlresearch

# Build settings
markdown: kramdown
theme: minima
