---
booktitle: Proceedings of the Eleventh International Conference on Artificial Intelligence
  and Statistics
series: Proceedings of Machine Learning Research
logo: SAIS_logo.jpg
volume: 2
year: '2007'
start: 2007-03-21
end: 2007-03-24
published: 2007-03-11
shortname: AISTATS
comments: false
bibsource: http://jmlr.csail.mit.edu/proceedings/
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
id: MeilaMSX2007
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Marina
  family: Meila
- given: Xiaotong
  family: Shen
description: |
  Proceedings of the Eleventh International Conference on Artificial Intelligence and Statistics
    Held in San Juan, Puerto Rico on 21-24 March 2007

  Published as Volume 2 by the Proceedings of Machine Learning Research on 11 March 2007.

  Volume Edited by:
    Marina Meila
    Xiaotong Shen

  Series Editors:
    Neil D. Lawrence
date_str: 21--24 Mar
url: http://proceedings.mlr.press
baseurl: "/v2"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v2
bibtex_copy: true
endnote_copy: true
apa_copy: true
email: ''
conference:
  name: Artificial Intelligence and Statistics
  url: http://users.stat.umn.edu/~aistat/
  location: San Juan, Puerto Rico
  dates:
  - 2007-03-21
  - 2007-03-22
  - 2007-03-23
  - 2007-03-24
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v2.bib
